FROM ubuntu:20.04

# update and upgrade
RUN apt-get update && apt-get upgrade -y

# install dependencies
RUN apt-get install -y build-essential curl git gnat libcurl4-gnutls-dev libgmp-dev libssl-dev gprbuild